spring:
  output:
    ansi:
      enabled: always
  datasource:
    dynamic:
      datasource:
        master:
          username: sa
          password: ""
          url: jdbc:h2:mem:test
          driver-class-name: org.h2.Driver
        slave_1:
          url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
        slave_2:
          username: root
          password: xxxxxx
          url: jdbc:oracle:thin:@127.0.0.1:18087:ORCL
          driver-class-name: oracle.jdbc.driver.OracleDriver
        slave_3:
          username: sa
          password: ""
          url: jdbc:h2:mem:test
          driver-class-name: org.h2.Driver